sima-land/ui-nucleons

src/helpers/__test__/media-query-list.test.ts, src/helpers/media-query-list.ts, src/hooks/breakpoint/utils.ts, src/hooks/media.ts
- добавлена утилитарная функция для подписки на событие `change` объекта `MediaQueryList` с учетом запуска в Safari < 14
- задействована новая функция подписки в хуках `useMedia` и `useBreakpoint`
Closes #42
=> Учесть использование MediaQueryList в Safari < 14

src/_internal/body-scroll.ts, src/context/viewport.ts, src/modal/index.tsx, src/modal/modal.module.scss, src/modal/slots.tsx, src/tooltip/__stories__/index.stories.tsx, src/with-tooltip/__stories__/index.stories.tsx, src/with-tooltip/__test__/__snapshots__/index.test.tsx.snap, src/with-tooltip/__test__/utils.test.ts, src/with-tooltip/positioning-tooltip.tsx, src/with-tooltip/utils.ts
- добавлен контекст для передачи элемента, формирующего viewport для выпадающих элементов
- задействован новый контекст в `Modal.Body`
- правки типов `useBodyScrollLock`
- мелкие правки stories `Tooltip`
- правки позиционирования тултипа в `WithTooltip`
Closes #41
=> WithTooltip: тултип выпадает за пределы Modal при отсутствии прокрутки у модального окна

src/unknown-content/unknown-content.module.scss
- `UnknownContent`: `margin-bottom` применялся не к `img, media` а к корневому элементу - исправлено
Closes #92
=> #92 UnknownContent: исправить установку отступов на корневой элемент

src/autocomplete/__stories__/index.stories.tsx, src/autocomplete/index.tsx, src/hooks/index.ts, src/phone-input/__test__/__snapshots__/index.test.tsx.snap, src/phone-input/__test__/index.test.tsx, src/phone-input/index.tsx, src/phone-input/phone-input.module.scss, src/select/__test__/__snapshots__/index.test.tsx.snap, src/select/index.tsx, src/text-field/__test__/index.test.tsx, src/text-field/index.tsx
- `PhoneInput`: убран `stopPropagation()` т.к. он из-за него не закрывались меню у других полей на странице (patch)
- `useOutsideClick`: мелкие правки типов (patch)
- `TextField`: разворот `blockProps` перенесен так чтобы не было возможности подменить свойства (minor)
- `Select`: правки после обновления `TextField` (patch)
Closes #114
=> #114  PhoneInput: убрать stopPropagation для кликов

src/modal/__test__/__snapshots__/index.test.tsx.snap, src/modal/__test__/index.test.tsx, src/modal/index.tsx, src/modal/slots.tsx
- Modal: слот Body теперь содержить BSL_IGNORE_ATTR
- Modal: по умолчанию содержит опцию allowTouchMove в пропсе bodyScrollLockOptions
Closes #141
=> #141  Modal: исправить блокировку прокрутки

src/screen/__test__/__snapshots__/index.test.tsx.snap, src/screen/__test__/index.test.tsx, src/screen/slots.tsx
- `Screen`: добавлен атрибут для корректной блокировки прокрутки на iOS (patch)
Closes #158
=> #158 Screen: убрать блокировку прокрутки на вложенных элементах

.prettierignore, src/carousel/__stories__/index.stories.tsx, src/carousel/__test__/draggable.test.tsx, src/carousel/__test__/index.test.tsx, src/carousel/draggable.tsx, src/carousel/index.tsx
- `Carousel`: экспериментальная попытка заменить обработку глобального события `resize` на использование `ResizeObserver` (patch)
=> #160 Carousel: исправить поведение на мобильных устройствах

src/autocomplete/__stories__/index.stories.tsx, src/autocomplete/__test__/index.test.tsx, src/autocomplete/index.tsx
- `Autocomplete`: экспериментальные правки, в Chrome при автозаполнении поля появляется меню (patch)
Closes #163
=> #163  Autocomplete: авто предзаполнение в Chrome почему-то открывает выпадающий список

src/link/__stories__/link.stories.tsx, src/link/index.tsx, src/link/link.module.scss, src/panel/__stories__/index.stories.tsx, src/panel/__test__/__snapshots__/index.test.tsx.snap, src/panel/__test__/index.test.tsx, src/panel/index.tsx, src/panel/panel.module.scss, src/side-page/__stories__/index.stories.tsx
- `Link`: добавлен вариант цвета `basic-blue` по обновленным гайдам
- `Link`: добавлена возможность задать подчеркивание пропом `underline`
- `Panel`: удален проп `inline`
- `Panel`: удален проп `color`
- `Panel`: удален проп `icon`
- `Panel`: удален проп `contentColor`
- `Panel`: удален проп `html`
- `Panel`: добавлен компонент `Panel.UnknownContent` для вывода неизвестной html-верстки
- `Panel`: добавлен проп `type` для формирования цветов по гайдам
- `Panel`: добавлены пропы `adornmentStart` и `adornmentEnd` для вывода иконок слева и справа
Closes #167
=> #167 Panel: Обновить в соответствии с новыми гайдами

src/bottom-bar/__test__/index.test.tsx, src/bottom-bar/index.tsx, src/breakpoints.scss, src/hooks/breakpoint/index.tsx, src/layout/__stories__/desktop.stories.tsx, src/layout/__stories__/index.stories.tsx, src/layout/__stories__/mobile.stories.tsx, src/layout/__test__/__snapshots__/index.test.tsx.snap, src/layout/__test__/index.test.tsx, src/layout/index.ts, src/layout/layout.tsx, src/layout/legacy.module.scss, src/layout/legacy.tsx, src/layout/types.ts, src/modal/__stories__/index.stories.tsx, src/modal/__test__/__snapshots__/index.test.tsx.snap, src/modal/index.tsx, src/modal/modal.module.scss, src/modal/slots.tsx, src/modal/utils.ts
- `Modal`: компонент обновлен в соответствии с новыми дизайн-гайдами (major)
- `BottomBar`: BottomBarSize теперь экспортируется (minor)
- `Layout`: добавлен новый единый компонент Layout для всех разрешений (minor)
- `useBreakpoint`: хук теперь не требует наличия BreakpointProvider в дереве (minor)
Closes #180
=> #180 Modal: обновить в соответствии с новыми дизайн-гайдами

src/_internal/checkbox/index.ts, src/checkbox/index.tsx, src/radio-button/index.tsx, src/switcher-row/__stories__/index.stories.tsx, src/switcher-row/index.tsx, src/toggle/index.tsx, src/types.ts
- internal: тип CheckboxProps перенесен в src/types.ts и переименован в CheckboxInputProps
- types: добавлены типы WithTestId, FieldProps
- checkbox: задействованы новые типы
- toggle: задействованы новые типы
- radio-button: задействованы новые типы
- switcher-row: удален проп failed из компонента
Closes #110
=> Шаг 2 #110 CheckboxField: доработать в соответствии с новыми дизайн-гайдами

src/carousel/__test__/draggable.test.tsx, src/carousel/draggable.tsx, src/checkbox/__stories__/index.stories.tsx, src/chips/__stories__/index.stories.tsx, src/field-grid/index.tsx, src/hooks/breakpoint/types.ts, src/hooks/breakpoint/utils.ts, src/types.ts
- carousel/draggable: правки обработки перетаскивания для исправления бага: не срабатывал первый клик после перетаскивания на touch-устройствах
- мелкие правки stories (patch)
- field-grid: добавлено пояснение для deprecated (patch)
- hooks/breakpoint: тип Breakpoint вынесен в src/types тк будет использоваться в Layout (patch)
=> #226 Carousel: не срабатывает первый клик после прокрутки на touch-устройствах

.github/workflows/npm-publish.yml, .github/workflows/tests-e2e.yml, .github/workflows/tests-unit.yml, .prettierignore, package.json, src/base-input/__test__/index.test.tsx, src/base-input/base-input.tsx, src/input/index.tsx, src/input/utils.ts, src/masked-field/__stories__/index.stories.tsx, src/masked-field/index.tsx
- `base-input`: теперь rest placeholder выводится только для контролируемых полей
- `input`: убраны any
- `masked-field`: помечен как deprecated
- `pacakge.json`: скрипты перенесены выше
- `.github`: подняты версии экшнов
- `.prettierignore`: больше не игнорируется yml, yaml
=> Шаг 1 #218 MaskedField: заменить TextField на Input

src/_internal/utils/dropdown.ts, src/autocomplete-deprecated/index.tsx, src/autocomplete/__stories__/index.stories.tsx, src/autocomplete/__test__/index.test.tsx, src/avatar/index.tsx, src/base-input-deprecated/index.tsx, src/carousel/draggable.tsx, src/carousel/helpers/draggable-event.ts, src/helpers/bounds-of.ts, src/helpers/center-of.ts, src/helpers/create-container.ts, src/helpers/find-child-element.ts, src/helpers/find-sibling-index.ts, src/helpers/get-date-interval-data.ts, src/helpers/get-declination.ts, src/helpers/get-relative-pos.ts, src/helpers/is-browser.ts, src/helpers/is-touch-device.ts, src/helpers/max-index-of.ts, src/helpers/on.ts, src/helpers/point.ts, src/helpers/rename.ts, src/helpers/with-prevent.ts, src/layout/legacy.tsx, src/loading-overlay/index.tsx, src/screen/index.tsx, src/select-deprecated/index.tsx, src/spinner/index.tsx, src/text-field/index.tsx
- добавлены пояснения для `deprecated`
- `helpers`: экспорты по умолчанию помечены как `deprecated`
- `autocomplete`: добавлены тесты
- `avatar`: убрано использование `any`
=> Шаг 2 #218 MaskedField: заменить TextField на Input

src/expandable/utils.ts, src/input/__test__/index.test.tsx, src/input/index.tsx, src/masked-input/__stories__/index.stories.tsx, src/masked-input/__test__/hook.test.tsx, src/masked-input/__test__/index.test.tsx, src/masked-input/hook.ts, src/masked-input/masked-input.tsx, src/masked-input/utils.ts, src/select/__stories__/index.stories.tsx, src/select/__test__/index.test.tsx, src/select/__test__/utils.test.tsx, src/select/parts/__test__/button.test.tsx, src/select/parts/button.tsx, src/select/parts/menu.tsx, src/select/select.tsx, src/select/types.ts, src/select/utils.ts
- `expandable`: правки использования хуков
- `input`: добавлена обработка пропса focused (зафиксировано тестами)
- `select`: `SelectProps` теперь содержит `defaultValue`
- `select`: `SelectProps` теперь содержит `renderValue`
- `select`: `SelectOpenerBinding` теперь содержит `anchorRef`
- `select`: `SelectOpenerBinding` - пропсы `onMouseDown, onKeyDown` теперь обязательны
- `select`: правки контекста в соответствии с новыми типам
- `select/parts/button`: теперь принимает пропсы `children, buttonRef, endIcon, iconGutter`
- `masked-input`: теперь не вызывает лишних перерендеров которые влекли скрытые баги (зафиксировано тестами)
- `select`: логика позиционирования меню вынесена из `SelectMenu` в `Select` чтобы соответствовать принципу передачи ref'ов
- `select`: добавлена возможность …
=> Шаг 2 #217 PhoneInput: обновить в соответствии с новыми дизайн-гайдами

playwright.config.ts, src/base-input/base-input.tsx, src/masked-input/__test__/index.test.tsx, src/masked-input/hook.ts, src/phone-input/__stories__/index.stories.tsx, src/phone-input/__test__/index.test.tsx, src/phone-input/__test__/utils.test.ts, src/phone-input/index.tsx, src/phone-input/phone-input.module.scss, src/phone-input/phone-input.tsx, src/phone-input/presets.ts, src/phone-input/types.ts, src/phone-input/utils.ts, src/upload-area/__test__/index.test.tsx, src/upload-area/upload-area.module.scss, src/upload-area/upload-area.tsx
- base-input: rest-placeholder теперь можно найти по data-testid
- base-input: теперь не выводит элемент rest-placeholder если value пустое
- masked-input: убраны костыли с ref'ами
- phone-input: добавлена новая реализация компонента PhoneInput
- мелкие доработки конфига pw
- upload-area: обводка solid теперь только при фокусе клавиатурой (убрана после клика)
=> Шаг 4 #217 PhoneInput: обновить в соответствии с новыми дизайн-гайдами

src/_internal/dropdown-loading/index.tsx, src/arrow-button/index.tsx, src/base-input/types.ts, src/dropdown/index.tsx, src/helpers/point.ts, src/hint/utils.ts, src/layout/__test__/__snapshots__/index.test.tsx.snap, src/layout/layout.module.scss, src/layout/layout.tsx
- мелкие todo (patch)
- мелкие правки типов (удалено использование глобального неймспейса React) (patch)
- layout: теперь не используются css-переменные (patch)
=> Шаг 1 #358 Отключить injectGlobals в Jest

src/carousel/__test__/index.test.tsx, src/carousel/carousel.tsx, src/carousel/draggable.tsx, src/carousel/helpers/__test__/draggable-event.test.ts, src/carousel/helpers/draggable-event.ts, src/helpers/__test__/find-child-index.test.ts, src/helpers/find-child-index.ts, src/hooks/breakpoint/index.tsx, src/stroked-svg/__stories__/index.stories.tsx, src/stroked-svg/stroked-svg.tsx, src/stroked-svg/types.ts, src/text-button/__stories__/index.stories.tsx, src/text-button/text-button.tsx, src/text-button/types.ts, src/with-hint/utils.ts, src/with-tooltip/__stories__/utils.tsx, src/with-tooltip/positioning-tooltip.tsx, src/with-tooltip/utils.ts
- убрано использование default import'ов утилит (patch)
- `text-button`: добавлена возможность задать unset для size, color, iconGutter (minor)
- `stroked-svg`: добавлена возможность задать data-testid (minor)
- `helpers`: модуль find-child-element переименован в find-child-index (major)
=> Шаг 1 #392 Удалить deprecated- компоненты и утилиты

package-lock.json, package.json, src/avatar/utils.tsx, src/context/__test__/index.test.tsx, src/hooks/use-intersection/__test__/index.test.tsx, src/hooks/use-intersection/__test__/test-utils.test.ts, src/hooks/use-intersection/test-utils.ts, src/test-utils/__test__/create-dom-rect-read-only.test.ts, src/test-utils/__test__/intersection-observer-mock.test.ts, src/test-utils/create-dom-rect-read-only.ts, src/test-utils/index.ts, src/test-utils/intersection-observer-mock.ts
- avatar: исправлено название внутренней константы (patch)
- hooks/use-intersection/test-utils: все утилиты помечены как deprecated (patch)
- test-utils: добавлены утилиты IntersectionObserverMock и createDOMRectReadOnly (minor)
- обновлен пакет typescript (patch)
=> Шаг 1 #413 Добавить моки web API для удобного использования вместе с соответствующими контекстами

src/context/index.ts, src/dropdown/__test__/utils.test.tsx, src/test-utils/__test__/resize-observer-mock.test.ts, src/test-utils/index.ts, src/test-utils/intersection-observer-mock.ts, src/test-utils/resize-observer-mock.ts
- test-utils: добавлен класс ResizeObserverMock (minor)
- test-utils: реализация реестра экземпляров IntersectionObserverMock вынесена в отдельный класс (patch)
- dropdown: переписаны unit-тесты (patch)
- context: мелкие правки комментариев (patch)
=> Шаг 2 #413 Добавить моки Web API для удобного использования вместе с соответствующими контекстами

src/base-input/__stories__/index.stories.tsx, src/base-input/base-input.m.scss, src/base-input/types.ts, src/field-block/field-block.m.scss, src/input/__test__/index.test.tsx, src/input/input.m.scss, src/input/input.tsx, src/textarea/__test__/index.test.tsx, src/textarea/textarea.tsx
- base-input: css-переменная --placeholder-color заменена на --base-input-placeholder-color (major)
- base-input: добавлена возможность задать css-переменные цвета и фона (minor)
- input: заданы цвета для BaseInput явно для правок в safari (patch)
- field-block: правки стилей из-за новой реализации base-input из-за Safari (patch)
=> Шаг 1 #424 Поля ввода текста: в Safari при disabled введенный текст не виден на фоне поля

docs/stories/components/masked-input/04-different-states.story.tsx, src/input/__test__/index.test.tsx, src/input/input.tsx, src/textarea/__test__/index.test.tsx, src/textarea/textarea.tsx, src/textarea/types.ts
- input: добавлена возможность переопределить `--base-input-placeholder-color`
- textarea: добавлена возможность переопределить `--base-input-placeholder-color`
- textarea: мелкие правки типов
=> #476 Input: добавить возможность переопределять css-переменную цвета плейсхолдера

src/carousel/__test__/draggable.test.tsx, src/carousel/draggable.tsx
- Исправлено поведение блокировки клика после драг-н-дропа в карусели: блокируем клик, если курсор в пределах карусели, иначе нет.
- Отображено в тестах, проверено локально
=> Не работает клик после драг-н-дропа в карусели

package-lock.json, package.json, src/custom.d.ts, src/masked-input/__test__/masked-input.test.tsx, src/masked-input/masked-input.tsx, src/masked-input/types.ts, src/phone-input/__test__/phone-input.test.tsx, src/phone-input/index.ts, src/phone-input/phone-input.tsx, src/phone-input/preset/defaults-import-png.ts, src/phone-input/preset/defaults.ts, src/phone-input/types.ts, tests/phone-input.spec.ts
- `MaskedInput` и `PhoneInput`
- добавлена логика и возможность прокинуть `prop` для минимального необходимо значения для расчета заполнености маски
- дефолтное значение для маски `Другое`  == `5 символов`
- сужен тип для `id` маски и добавлены недостающие экспорты
- `сборка и конфиг`
- поправлен тип для картинок
- обновлен `prettier`, т.к `pre-commit hook` подменял `singleQuote` на `doubleQuote`
- прогнан `audit fix`
=> #12351 Реализовать возможность отключать проверку на заполненность маски при достижении минимального необходимого значения
