sima-land/ui-nucleons

- src/link/__stories__/link.stories.tsx
- src/link/__test__/__snapshots__/index.test.tsx.snap
- src/link/index.tsx
- src/link/link.module.scss
- увеличена специфичность стилей Link для монолита
> #4 Увеличить специфичность стилей Link для монолита

- .github/workflows/tests.yml
- package.json
- добавлен action с тестами на MR и пуш в мастер
- удалены лишние скрипты
> Запуск тестов, линтера и проверки типов для MR #13

- .jest/setup.js
- .storybook/preview.js
- readme.md
- src/hooks/breakpoint/__stories__/breakpoint.stories.tsx
- src/hooks/breakpoint/__test__/index.test.tsx
- src/hooks/breakpoint/__test__/utils.test.ts
- src/hooks/breakpoint/index.tsx
- src/hooks/breakpoint/types.ts
- src/hooks/breakpoint/utils.ts
- добавлен хук `useBreakpoint`
- добавлены тесты и stories
- правки конфигов jest/storybook
- правки readme
Closes #26
> Хук useBreakpoint

- package.json
- src/panel/__test__/__snapshots__/index.test.tsx.snap
- yarn.lock
- обновлен пакет иконок
- обновлены снепшоты
Closes #28
> Обновление пакета иконок 

- src/base-input/__test__/index.test.tsx
- src/base-input/index.tsx
- src/text-field/__stories__/index.stories.tsx
- BaseInput: подгон высоты теперь выполняется при каждом рендере
- добавлены тесты
- добавлены stories
Closes #30
> BaseInput: подгон высоты теперь выполняется при каждом рендере

- src/dot-nav/__stories__/index.stories.tsx
- src/dot-nav/__test__/__snapshots__/index.test.tsx.snap
- src/dot-nav/__test__/index.test.tsx
- src/dot-nav/dot-nav.module.scss
- src/dot-nav/index.tsx
- src/rating/__stories__/index.stories.tsx
- src/touch-slider/__stories__/index.stories.tsx
- DotNav: добавлена возможность задавать размер
- Rating, TouchSlider: мелкие правки stories не по задаче
Closes #45
> DotNav: возможность задавать размер по гайдам

- src/_internal/checkbox/index.ts
- src/checkbox-field/__stories__/index.stories.tsx
- src/checkbox-field/__test__/__snapshots__/index.test.tsx.snap
- src/checkbox-field/__test__/index.test.tsx
- src/checkbox-field/checkbox-field.module.scss
- src/checkbox-field/index.tsx
- src/checkbox/__test__/__snapshots__/index.test.tsx.snap
- src/checkbox/checkbox.module.scss
- src/checkbox/index.tsx
- src/toggle/__stories__/index.stories.tsx
- src/toggle/__test__/__snapshots__/index.test.tsx.snap
- src/toggle/index.tsx
- синхронизированы интерфейсы Checkbox и Toggle (major change)
- обновлен CheckboxField в соответствии с новыми гайдами (major change)
Closes #47
> CheckboxField: Правки по новым гайдам

- package.json
- src/text/__stories__/index.stories.tsx
- src/text/__test__/__snapshots__/index.test.tsx.snap
- src/text/__test__/index.test.tsx
- src/text/index.tsx
- src/text/text.module.scss
- yarn.lock
- Text: проп truncate теперь может получать числовое значение
- Text: удален проп italic (по гайдам не используем)
- добавлены тесты и stories
- обновлен typescript
Closes #49
> #49 Text: добавлена возможность задать line-clamp и удален проп italic

- src/stepper/__stories__/index.stories.tsx
- src/stepper/__test__/__snapshots__/index.test.tsx.snap
- src/stepper/__test__/index.test.tsx
- src/stepper/index.tsx
- src/stepper/stepper.module.scss
- Stepper: добавлен ref-проп для поля
- Stepper: добавлены стили для состояний "readonly"
- Stepper: добавлено визуально состояние "failed"
> Доработки Stepper

- src/checkbox/__stories__/checkbox.stories.tsx
- src/checkbox/__test__/index.test.tsx
- src/checkbox/index.tsx
- правки работы Checkbox (неверно обрабатывался defaultChecked)
> Fix #47 Правки поведения Checkbox c пропом defaultChecked

- src/alert/__test__/__snapshots__/index.test.tsx.snap
- src/nav-bar/__test__/__snapshots__/index.test.tsx.snap
- src/nav-bar/index.tsx
- src/nav-bar/nav-bar.module.scss
- src/screen/__test__/__snapshots__/index.test.tsx.snap
- NavBar: высота теперь задается публичной константой
- обновлены snapshot'ы
Closes #54
> NavBar: Добавлена публичная константа высоты компонента

- src/dot-nav/dot-nav.module.scss
- правки вичислений в calc для решения проблемы cssnano
Closes #74
> #74 DotNav: упросить вычисление размера

- src/alert/__stories__/index.stories.tsx
- src/alert/__test__/__snapshots__/index.test.tsx.snap
- src/alert/__test__/index.test.tsx
- src/alert/index.tsx
- Alert: добавлен проп onClose по аналогии с Modal
Closes #76
> #76 Alert: добавлена возможность закрывать по тапу на затемнение

- .storybook/main.js
- .storybook/webpack.config.js
- package-lock.json
- package.json
- правки сборки Storybook после перехода на NPM и обновления зависимостей
> Fix #78 Переход на NPM 

- src/tabs/__stories__/tabs.stories.tsx
- src/tabs/__test__/__snapshots__/index.test.tsx.snap
- src/tabs/__test__/index.test.tsx
- src/tabs/index.tsx
- src/tabs/tabs.module.scss
- `Tabs`: обновлен подход к формированию содержимого (major changes)
- `Tabs`: обновлены пропсы влияющие на внешний вид (major changes)
- обновлены тесты, stories
Closes #81
> #81 Обновлен компонент Tabs

- src/chips/__stories__/index.stories.tsx
- src/chips/__test__/__snapshots__/index.test.tsx.snap
- src/chips/__test__/index.test.tsx
- src/chips/index.tsx
- src/chips/item.tsx
- Chips: формирование содержимого переделано на слоты
- правки тестов, stories
Closes #85
> #85 ChipsItem: переделать на слоты

- src/side-page/__stories__/index.stories.tsx
- src/side-page/index.tsx
- SidePage: добавлен проброс callback'ов смены статуса анимации CSSTransition
- добавлен пример ленивой загрузки в Storybook
Closes #87
> #87 SidePage: добавить callback'и onEnter и onExited

- src/side-page/__stories__/index.stories.tsx
- src/side-page/__test__/index.test.tsx
- src/side-page/index.tsx
- SidePage: задействован LayerProvider (некорректно выводились всплывающие элементы)
- добавлены тесты,  stories
Closes #100
> #100 SidePage: задействовать LayerProvider

- src/select/__stories__/index.stories.tsx
- src/select/__test__/__snapshots__/index.test.tsx.snap
- src/select/__test__/index.test.tsx
- src/select/index.tsx
- src/text-field/index.tsx
- Select: правки обработки клика при раскрытом списке
- TextField: добавлен авозможность задавать пропсы блока
Closes #91
> #91 Select: разобраться с кликом по полю с раскрытым списком

- src/alert/__test__/__snapshots__/index.test.tsx.snap
- src/alert/__test__/index.test.tsx
- src/alert/index.tsx
- src/modal/__stories__/index.stories.tsx
- src/modal/__test__/__snapshots__/index.test.tsx.snap
- src/modal/__test__/index.test.tsx
- src/modal/index.tsx
- src/modal/utils.ts
- src/with-tooltip/__stories__/index.stories.tsx
- `Alert`: удален проп `inPortal`
- `Modal`: удален проп `inPortal`
Closes #103
> #103  Избавиться от inPortal

- src/select/__stories__/index.stories.tsx
- src/select/index.tsx
- `Select`: исправлено игнорирование пропа `size`
- Добавлены stories для визуальной фиксации работоспособности
> Fix | #91 

- src/select/__stories__/index.stories.tsx
- src/select/__test__/index.test.tsx
- src/select/index.tsx
- добавлена возможность выводить кастомную иконку в поле Select
- добавлены тесты, stories
Closes #106
> #106 Select: добавить возможность выводить произвольную иконку

- src/carousel/__test__/index.test.tsx
- src/carousel/index.tsx
- src/helpers/find-child-element.ts
- Carousel: удалены typecast'ы, добавлены проверки типов в runtime (patch)
Closes #108
> #108  Carousel: Убрать typecast при определении viewport'а

- src/phone-input/__test__/index.test.tsx
- src/phone-input/index.tsx
- PhoneInput: добавлено закрытие списка при клике на иконку с открытым списком
Fix #114
> #114 PhoneInput: добавлено закрытие списка при клике на иконку

- src/arrow-button/__stories__/index.stories.tsx
- src/arrow-button/index.tsx
- src/avatar/__stories__/index.stories.tsx
- src/base-input/base-input.module.scss
- src/layout/__stories__/desktop.stories.tsx
- src/layout/__stories__/mobile.stories.tsx
- src/range/index.tsx
- src/touch-slider/__stories__/index.stories.tsx
- src/touch-slider/__test__/__snapshots__/index.test.tsx.snap
- src/touch-slider/__test__/index.test.tsx
- src/touch-slider/index.tsx
- src/touch-slider/touch-slider.module.scss
- src/utils.scss
- `ArrowButton`: добавлен экспорт типов размера кнопки и направления стрелки (minor)
- `Avatar`: мелкие правки stories (patch)
- `BaseInput`: задействован scss-mixin hidden-scrollbars (patch)
- `MobileLayout`: мелкие правки stories (patch)
- `DesktopLayout`: мелкие правки stories (patch)
- `Range`: мелкие правки типов (patch)
- `TouchSlider`: обновлена обрезка контента по гайдам (patch)
- добавлен scss-mixin "hidden-scrollbars" (minor)
> #120  TouchSlider: обновить отсутпы по гайдам

- src/chips/__stories__/index.stories.tsx
- src/chips/chips.module.scss
- `Chips`: чипсы-ссылки теперь корректно отображают состояние `checked` (patch)
Closes #132
> #132  Chips: ссылка может иметь состояние checked

- src/carousel/index.tsx
- src/expandable/__stories__/index.stories.tsx
- src/expandable/__test__/utils.test.tsx
- src/expandable/index.tsx
- src/expandable/utils.ts
- `Expandable`: добавленоо обновление состояния отображения при ререндере (patch)
- `Carousel`: добавлена возможность задавать className для кнопок (patch)
Closes #137
> #137 Expandable: придумать как реагировать на rerender и другие события

- src/clean-buttons/__stories__/index.stories.tsx
- src/clean-buttons/index.tsx
- src/expandable/__stories__/index.stories.tsx
- src/expandable/__test__/index.test.tsx
- src/expandable/index.tsx
- `Expandable`: добавлена возможность управлять состоянием извне через проп expanded (minor)
- `Clean.Group`: правки вывода документации в Storybook (patch)
Closes #138
> #138  Expandable: добавить возможность выводить закрывашку

- src/expandable/__test__/index.test.tsx
- src/expandable/__test__/utils.test.tsx
- src/expandable/expandable-group.module.scss
- src/expandable/index.tsx
- src/expandable/utils.ts
- Expandable: верстка сделана более-менее семантичной (patch)
- Expandable: открывашка больше не показывается в SSR (для SEO) (patch)
- Expandable: изменена реализация пересчета видимости (меньше хуков, проще логика, в обход react) (patch)
Closes #143
> #143  Expandable: доработать семантику верстки

- src/stepper/__test__/__snapshots__/index.test.tsx.snap
- src/stepper/index.tsx
- src/stepper/stepper.module.scss
- Stepper: внешний вид обновлен в соответствии с новыми дизайн-гайдами (patch)
- Stepper: ослаблены типы callback'ов onAdd, onSubtract (patch)
Closes #147
> #147 Stepper: обновить по новым дизайн-гайдам

- src/stepper/stepper.module.scss
> Fix | #147

- .prettierignore
- src/text-field/text-field.module.scss
- TextField: обновлен цвет валиации по согласованию с дизайнерами (patch)
Closes #151
> #151  TextField: обновить цвет валидации

- src/_internal/body-scroll.ts
- src/modal/__stories__/index.stories.tsx
- хук блокировки прокрутки теперь использует layout effect
- Modal: добавлены stories для проверки блокировки прокрутки при переключении
> Шаг 1 #124  Modal: реализовать решение для исправления "скачков" полосы прокрутки

- src/range/__test__/__snapshots__/index.test.tsx.snap
- src/range/__test__/index.test.tsx
- src/range/index.tsx
- `Range`: кнопкам добавлены атрибуты aria-label SEO (patch)
- `Range`: тесты переписаны с enzyme на testing-library/react
Closes #156
> #156  Внести доработки в компоненты для SEO

- src/checkbox/checkbox.module.scss
- Checkbox: добавлен `cursor: pointer` при наведении
Closes #165
> #165  Checkbox: добавить cursor:pointer при наведении

- src/panel/panel.module.scss
- `Panel`: правки позиционирования иконок
> Fix | #167

- src/alert/__test__/__snapshots__/index.test.tsx.snap
- src/alert/index.tsx
- src/top-bar/top-bar.module.scss
- `TopBar`: правки стилей, не было отступов когда не заданы кнопки (patch)
> Fix | #170

- src/radio-button/__stories__/index.stories.tsx
- src/radio-button/__test__/__snapshots__/index.test.tsx.snap
- src/radio-button/__test__/index.test.tsx
- src/radio-button/index.tsx
- src/radio-button/radio-button.module.scss
- добавлен компонент radio-кнопки
Closes #171
> #171  Добавить компонент radio-кнопки

- src/field-block/__stories__/index.stories.tsx
- src/field-block/__test__/__snapshots__/index.test.tsx.snap
- src/field-block/__test__/index.test.tsx
- src/field-block/field-block.module.scss
- src/field-block/index.tsx
- src/loading-overlay/__stories__/index.stories.tsx
- src/loading-overlay/index.tsx
- src/toggle/__stories__/index.stories.tsx
- src/toggle/toggle.module.scss
- Toggle: правки отображения (patch)
- LoadingOverlay: помечен как deprecated (patch)
- FieldBlock: добавлен компонент (minor)
Closes #168
> #168 Добавить служебный компонент FieldBlock

- .storybook/index.stories.mdx
- .storybook/main.js
- src/button/__stories__/button.stories.tsx
- src/button/button.module.scss
- src/button/index.tsx
- src/field-block/field-block.module.scss
- src/input/__stories__/index.stories.tsx
- src/input/__test__/index.test.tsx
- src/input/utils.ts
- src/textarea/__stories__/index.stories.tsx
- src/textarea/__test__/index.test.tsx
- src/textarea/index.tsx
- src/textarea/textarea.module.scss
- `FieldBlock`: правки стилей по гайдам
- `Input`: удалены пропсы `onClick, onMouseDown`
- `Input`: добавлены популярные пропсы элемента input
- `Button`: правки stories
- `Button`: теперь экспортируются типы `ButtonSize, ButtonViewType, ButtonProps`
- `Button`: иконкам добавлен `flex-shrink: 0`
- добавлен компонент `Textarea`
- storybook: добавлена базовая приветственная страница
Closes #169
> Шаг 2 #169 Добавить компоненты Input и Textarea

- src/text-button/__stories__/index.stories.tsx
- src/text-button/__test__/index.test.tsx
- src/text-button/index.tsx
- src/text-button/text-button.module.scss
- добавлен компонент `TextButton` (minor)
> Шаг 1 #162 Select: обновить в соответствии с новыми дизайн-гайдами + исправить баги

- src/select/__stories__/index.stories.tsx
- src/select/__test__/index.test.tsx
- src/select/__test__/utils.test.tsx
- src/select/select.tsx
- src/select/utils.tsx
- Select: опции disabled теперь игнорируются мышкой и клавиатурой
> Fix | #162

- src/_internal/dropdown-loading/index.tsx
- src/base-input/__stories__/index.stories.tsx
- src/base-input/__test__/index.test.tsx
- src/base-input/base-input.module.scss
- src/base-input/base-input.tsx
- src/base-input/index.ts
- src/base-input/types.ts
- src/base-input/utils.ts
- src/card/slots.tsx
- src/clean-buttons/index.tsx
- src/dropdown-item/__stories__/index.stories.tsx
- src/dropdown/__stories__/index.stories.tsx
- src/field-block/field-block.module.scss
- src/helpers/fit-element-height.ts
- src/screen/__stories__/utils.tsx
- src/select-deprecated/__test__/__snapshots__/index.test.tsx.snap
- fitElementHeight: правки для firefox 106
- DropdownItem: stories перенесены в раздел common
- Dropdown: stories перенесены в раздел common
- FieldBlock: правки стилей label
- добавлена обновленная реализация BaseInput
- мелкие правки типов
- мелкие правки хука useViewportVars
> Шаг 2 #194 Autocomplete: обновить в соответствии с новыми дизайн-гайдами

- src/dropdown-item/__test__/utils.test.tsx
- src/dropdown-item/types.ts
- src/dropdown-item/utils.ts
- src/input/__test__/index.test.tsx
- src/input/index.tsx
- src/select/__stories__/index.stories.tsx
- src/select/__test__/index.test.tsx
- src/select/__test__/utils.test.tsx
- src/select/select.tsx
- src/select/types.ts
- src/select/utils.tsx
- src/textarea/__test__/index.test.tsx
- src/textarea/index.tsx
- `Select`: проп `onChange` заменен в `onValueChange`
- `MenuItem, MenuItemElement`: перенесены и переименованы в `DropdownItemUtils`, `DropdownItemElement`
- `Input`: задействована новая версия `BaseInput`
- `Textarea`: задействована новая версия `BaseInput`
- `Input, Textarea`: добавлены свойства `style`, `className` для стилизации корневых элементов
> Шаг 3 #194 Autocomplete: обновить в соответствии с новыми дизайн-гайдами

- .jest/setup.js
- src/autocomplete/__stories__/index.stories.tsx
- src/autocomplete/__test__/index.test.tsx
- src/autocomplete/autocomplete.module.scss
- src/autocomplete/autocomplete.tsx
- src/autocomplete/index.tsx
- src/autocomplete/types.ts
- src/dropdown/utils.ts
- src/modal/__test__/__snapshots__/index.test.tsx.snap
- src/side-page/__stories__/index.stories.tsx
- src/text-button/index.tsx
- добавлен компонент Autocomplete
- TextButton: добавлен экспорт типов TextButtonAsButtonProps, TextButtonAsAnchorProps
- SidePage: в stories TextField заменен на Textarea
- добавлен хук useFloatingDropdown
- правки конфигурации тестов
> Шаг 5 #194 Autocomplete: обновить в соответствии с новыми дизайн-гайдами

- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- .gitignore
- jest.config.js
- package-lock.json
- package.json
- playwright.config.ts
- src/field-block/__test__/__snapshots__/index.test.tsx.snap
- src/field-block/index.tsx
- tests/select.spec.ts
- добавлены пакеты Playwright
- добавлена job'а в CI с e2e-тестами
- FieldBlock: добавлен data-testid для основного слота
- правки конфигурации Jest чтобы не конфликтовал с Playwright
- Select: добавлены базовые e2e-тесты
> Шаг 7 #194 Autocomplete: обновить в соответствии с новыми дизайн-гайдами

- .jest/setup.js
- src/clean-buttons/__test__/__snapshots__/index.test.tsx.snap
- src/clean-buttons/__test__/index.test.tsx
- src/clean-buttons/index.tsx
- src/helpers/__test__/styles.test.ts
- src/helpers/styles.ts
- src/hooks/__test__/styles.test.tsx
- src/hooks/index.ts
- src/hooks/styles.ts
- src/top-bar/__test__/utils.test.ts
- src/top-bar/top-bar.module.scss
- src/top-bar/utils.tsx
- CleanButtons: const >> function
- hooks/index: const >> function
- helpers/styles: добавлена утилита setViewportHeightUnit
- hooks/styles: добавлен хук useViewportHeightUnit
- правки конфига jest для работы с visualViewport
- top-bar/utils: добавлена утилита presetButtons для быстрого формирования иконок "назад" и "закрыть"
- top/bar: правки стилей кнопок-иконок для Safari
> Шаг 2 #175 Alert: переделать на слоты

- .storybook/main.js
- .storybook/utils.tsx
- package-lock.json
- package.json
- src/modal-overlay/__test__/index.test.tsx
- src/modal-overlay/index.tsx
- src/modal-overlay/modal-overlay.module.scss
- src/modal-overlay/utils.ts
- src/select/__stories__/index.stories.tsx
- добавлен пакет lorem-ipsum
- `modal-overlay`: добавлен компонент ModalOverlay
- `.storybook/utils`: добавлена утилита LoremIpsum
- `.storybook/main`: некоторые аддоны теперь отключаются в CI
- `select`: Мелкие правки stories
> Шаг 4 #175  Alert: переделать на слоты

- .storybook/utils.tsx
- src/_internal/__test__/body-scroll.test.tsx
- src/_internal/custom-scrollbar/__test__/index.test.tsx
- src/_internal/custom-scrollbar/index.tsx
- src/alert/__stories__/index.stories.tsx
- src/alert/__test__/index.test.tsx
- src/modal/__stories__/index.stories.tsx
- src/modal/__test__/__snapshots__/index.test.tsx.snap
- src/modal/__test__/index.test.tsx
- src/modal/index.tsx
- src/modal/modal.module.scss
- src/modal/slots.tsx
- src/modal/utils.ts
- src/side-page/__stories__/index.stories.tsx
- src/side-page/__test__/__snapshots__/index.test.tsx.snap
- src/side-page/__test__/index.test.tsx
- src/side-page/index.tsx
- src/side-page/side-page.module.scss
- src/side-page/slots.tsx
- `Alert, Modal, SidePage`: переведены на новый механизм блокировки прокрутки страницы
- `.storybook/utils`: добавлен компонент - пример страницы для проверки блокировки прокрутки
> Шаг 6 #175 Alert: переделать на слоты

- reference.md
- src/modal-overlay/modal-overlay-util.scss
- src/modal-overlay/modal-overlay.module.scss
- src/side-page/__stories__/index.stories.tsx
- src/side-page/__test__/__snapshots__/index.test.tsx.snap
- src/side-page/index.tsx
- src/side-page/side-page.module.scss
- src/side-page/slots.tsx
- modal-overlay: цвет вынесен в отдельный scss файл
- side-page: обновлен по дизайн-гайдам, добавлена адаптивность
- reference.md дополнен информацией о кастомизации и unit-тестиовании компонентов
> Шаг 3 #204 SidePage: обновить в соответствии с новыми дизайн-гайдами

- .husky/pre-push
- package-lock.json
- package.json
- src/masked-input/__stories__/index.stories.tsx
- src/masked-input/__test__/hook.test.tsx
- src/masked-input/__test__/index.test.tsx
- src/masked-input/hook.ts
- src/masked-input/index.ts
- src/masked-input/masked-input.tsx
- src/masked-input/types.ts
- src/masked-input/utils.ts
- обновлены пакеты `@storybook/*`
- обновлен пакет `webpack`
- обновлен пакет `@krutoo/input-mask`
- добавлен пакет `redux`
- добавлен компонент `MaskedInput`
- хук `pre-push` теперь проверяет только типы
Closes #218
> Шаг 3 #218 MaskedField: заменить TextField на Input

- package-lock.json
- package.json
- src/autocomplete/autocomplete.tsx
- src/dropdown/utils.ts
- src/phone-input/__test__/index.test.tsx
- src/select/__stories__/index.stories.tsx
- src/select/__test__/index.test.tsx
- src/select/parts/block.tsx
- src/select/parts/button.tsx
- src/select/select.tsx
- src/select/types.ts
- dropdown: обновлены утилиты позиционирования
- select: правки использования dropdown
- autocomplete: правки использования dropdown
- добавлен пакет `@testing-library/user-event`
- правки тестов
> Шаг 3 #238 Реализовать компонент Popup по дизайн-гайдам

- src/popup/__stories__/index.stories.tsx
- src/popup/__test__/index.test.tsx
- src/popup/index.tsx
- src/popup/popup-view.module.scss
- src/popup/popup-view.tsx
- src/popup/popup.tsx
- src/popup/utils.ts
> Шаг 5 #238 Реализовать компонент Popup по дизайн-гайдам

- .github/actions/publish-notify/action.yml
- .github/workflows/npm-publish.yml
- tests/popup.spec.ts
- правки оповещений (неправильно работали)
- правки селекторов в e2e для Popup
> Шаг 1 #247 Hint: обновить в соответствии с дизайн-гайдами

- src/hint/__stories__/hint-view.stories.tsx
- src/hint/__stories__/hint.stories.tsx
- src/hint/__test__/index.test.tsx
- src/hint/hint-view.module.scss
- src/hint/hint-view.tsx
- src/hint/hint.tsx
- src/hint/index.ts
- src/hint/utils.ts
- добавлены компоненты Hint и HintView
- добавлены хуки для реализации всплывающих хинтов
- добавлены тесты
- добавлены stories
> Шаг 3 #247 Hint: обновить в соответствии с дизайн-гайдами

- src/autocomplete/types.ts
- src/dropdown/index.tsx
- src/hint/hint.tsx
- src/info-text/index.tsx
- src/phone-input/types.ts
- src/popup/utils.ts
- src/rating/index.tsx
- мелкие правки JSDoc
Closes #247
> Шаг 4 #247 Hint: обновить в соответствии с дизайн-гайдами 

- readme.md
- src/colors/__stories__/index.stories.tsx
- src/dropdown/utils.ts
- src/hint/__stories__/hint-view.stories.tsx
- src/hint/__stories__/hint.stories.tsx
- src/hint/hint-view.module.scss
- src/link/__stories__/link.stories.tsx
- src/link/index.tsx
- src/link/link-util.scss
- src/link/link.module.scss
- src/text-button/__stories__/index.stories.tsx
- src/text-button/text-button.module.scss
- link: добавлен миксин color в link-utils.scss
- link: компонент Link теперь может принимать 2 новых цвета (additional-red и additional-teal)
- text-button: компонент TextButton теперь может принимать новые цвета (additional-red и additional-teal)
- colors: правки stories
- dropdown: добавлен todo с пояснением
- hint: правки stories
- hint: стрелке добавлен `z-index: -1`
- правки readme
> #252 TextButton: доработать в соответствии с новыми дизайн-гайдами

- .storybook/index.stories.mdx
- .template/build.mjs
- .template/colors.scss.handlebars
- .template/colors.ts.handlebars
- readme.md
- src/arrow-button/__stories__/index.stories.tsx
- src/autocomplete/__stories__/index.stories.tsx
- src/avatar/__test__/__snapshots__/user.test.tsx.snap
- src/box/__stories__/box.stories.tsx
- src/clean-buttons/__stories__/index.stories.tsx
- src/colors.scss
- src/colors/index.ts
- src/dot-nav/__stories__/index.stories.tsx
- src/link/__stories__/link.stories.tsx
- src/radio-button/__stories__/index.stories.tsx
- src/screen/__stories__/index.stories.tsx
- src/text/__stories__/index.stories.tsx
- src/tooltip/__stories__/index.stories.tsx
- удалено использование storybook-addon-actions
- мелкие правки главной страницы
- добавлен коммент к генерируемым файлам
> Шаг 1 #256 Доработки по результатам использования alpha.0

- src/breakpoints.scss
- src/select/__stories__/index.stories.tsx
- src/select/parts/block.module.scss
- src/select/parts/block.tsx
- src/switcher-row/index.tsx
- src/switcher-row/switcher-row.module.scss
- select: исправлено переполнение поля текстом
- switcher-row: для Checkbox/RadioButton расстояние между полем и текстом 8 вместо 12
- breakpoints: добавлены более явные миксины а старые помечены как deprecated
Closes #256
> Шаг 2 #256 Доработки по результатам использования alpha.0

- src/bottom-bar/bottom-bar.tsx
- src/bottom-bar/index.ts
- src/hooks/index.ts
- src/hooks/keydown.ts
- src/modal-overlay/modal-overlay.module.scss
- src/modal/modal.module.scss
- bottom-bar: правки импортов типов
- modal-overlay, modal: попытка исправить отображение на страницах с body min-width
- hooks: хук keydown теперь проверят клик на этапе захвата события
Closes #261
> #261 Разобраться с размером модальных окон на мобильных устройствах

- src/alert/__stories__/index.stories.tsx
- src/avatar/avatar.module.scss
- src/box/__stories__/box.stories.tsx
- src/carousel/__stories__/index.stories.tsx
- src/carousel/__stories__/test-carousel.module.scss
- src/hint/utils.ts
- src/masked-input/__stories__/index.stories.tsx
- src/screen/__stories__/index.stories.tsx
- src/screen/__stories__/stories.module.scss
- src/styling/borders.ts
- src/styling/colors.ts
- src/styling/fonts.ts
- src/styling/shadows.ts
- src/styling/shapes.ts
- src/styling/sizes.ts
- src/styling/utils.ts
- src/text/__stories__/index.stories.tsx
- src/utils.scss
- Text и Box помечены как deprecated в storybook
- styling: утилиты помечены как deprecated, необходимо использовать миксины вместо них или обычный css
- avatar: правки для вывода внутри ссылок с decoration: underline
- carousel: в сторибук добавлен пример с рилсами
- hint: хук useHintOnHover больше не содержит задержки но содержит безопасный прямоугольник
- masked-input: в сторибук добавлен пример с полем даты (пока нет DateInput)
- screen: в сторибук добавлен пример с доп топбаром
- styling: утилиты помечены как deprecated, надо использовать миксины или обычный css
- utils.scss: декомпозирован миксин focus-visible
Closes #263
> #263 Внести доработки по результатам использования

- .jest/setup.js
- src/group-overflow/__stories__/index.stories.tsx
- src/group-overflow/__test__/index.test.tsx
- src/group-overflow/__test__/utils.test.tsx
- src/group-overflow/group-overflow.module.scss
- src/group-overflow/index.tsx
- src/group-overflow/utils.ts
- добавлен компонент GroupOverflow
Closes #266
> #266 Реализовать компонент GroupOverflow

- src/group-overflow/__stories__/index.stories.tsx
- GroupOverflow: добавлен пример с искусственным ограничением числа элементов
> Шаг 2 #266

- src/modal/index.tsx
- src/top-bar/__stories__/index.stories.tsx
- src/top-bar/types.ts
- modal: добавлена возможность отключать заглушку футера
- top-bar: добавлена возможность выводить ReactNode в title и subtitle
Closes #265
> #265 Modal: Добавить возможность убрать заглушку футера и выводить кастомный заголовок

- src/arrow-button/arrow-button.module.scss
- src/avatar/index.tsx
- src/avatar/utils.ts
- src/group-overflow/index.tsx
- src/hint/__stories__/hint-view.stories.tsx
- src/hint/__stories__/hint.stories.tsx
- src/hint/__test__/index.test.tsx
- src/hint/utils.ts
- src/text-button/text-button.module.scss
- src/top-bar/index.ts
- `hint`: теперь `useTempHintState` по умолчанию скрывает хинт через 3сек
- `hint`: теперь `useTempHintState` принимает опцию timeout вторым аргументом
- `arrow-button`: миксины теней вместо классов из styling
- `avatar`: удален lodash
- `group-overflow`: правки интерпретации пропа gap
- `text-button`: из стилей удален сброс margin
- `top-bar`: исправлен экспорт `navigationButtons`
Closes #270
> #270 Hint: обновить длительность временного хинта и добавить возможность менять это время

- src/pagination-deprecated/__stories__/pagination.stories.tsx
- src/pagination-deprecated/__test__/__snapshots__/base-pagination.test.tsx.snap
- src/pagination-deprecated/__test__/__snapshots__/index.test.tsx.snap
- src/pagination-deprecated/__test__/__snapshots__/page-button.test.tsx.snap
- src/pagination-deprecated/__test__/base-pagination.test.tsx
- src/pagination-deprecated/__test__/index.test.tsx
- src/pagination-deprecated/__test__/page-button.test.tsx
- src/pagination-deprecated/__test__/utils.test.ts
- src/pagination-deprecated/base-pagination.tsx
- src/pagination-deprecated/index.tsx
- src/pagination-deprecated/page-button.tsx
- src/pagination-deprecated/pagination.module.scss
- src/pagination-deprecated/utils.ts
- src/select-deprecated/__test__/__snapshots__/index.test.tsx.snap
- src/select-deprecated/__test__/index.test.tsx
- `pagination-deprecated`: устаревшая версия взята из релиза `45.0.0-alpha.4`
> Шаг 5 #284 Pagination: обновить в соответствии с измененными дизайн-гайдами

- src/pagination/__stories__/index.stories.tsx
- src/pagination/pagination-item.module.scss
- src/pagination/pagination.module.scss
- src/pagination/pagination.tsx
- pagination: добавлено уменьшение текста для больших чисел по дизайн-гайдам
> Шаг 6 #284 Pagination: обновить в соответствии с измененными дизайн-гайдами

- src/button/__stories__/button.stories.tsx
- src/button/__test__/index.test.tsx
- src/button/button.module.scss
- src/button/index.tsx
- button: добавлена возможность задать viewType: success
> Шаг 1 #301 Button: обновить в соответствии с новыми дизайн-гайдами #301 

- src/button/__stories__/button.stories.tsx
- src/button/button-util.scss
- src/button/button.module.scss
- src/button/index.tsx
- button: добавлена возможность задавать произвольные цвета указав viewType='unset' и задав нужные css-переменные вручную
- button: добавлен экспорт типа ButtonStyle
- button: добавлены миксины цвета и размера в `button-util.scss`
Closes #301
> Шаг 2 #301 Button: обновить в соответствии с новыми дизайн-гайдами

- src/avatar/__stories__/index.stories.tsx
- avatar: добавлен пример смены размера в storybook
> Шаг 2 #307

- src/expandable/index.tsx
- src/textarea/index.tsx
- src/top-bar/top-bar.module.scss
- Textarea: размер по умолчанию теперь 2 строки в соответствии с дизайн-гайдами (patch)
- TopBar: расстояние между заголовком и подзаголовком теперь -2px а не -4px в соответствии с дизайн-гайдами (patch)
- Expandable: теоретический фикс для SSR (patch)
Closes #311 
Closes #312
> #311, #312 мелкие изменения для соответствия обновлениям в гайдах

- src/autocomplete/autocomplete.tsx
- src/bottom-bar/__stories__/index.stories.tsx
- src/hint/__stories__/hint-view.stories.tsx
- src/pagination/__test__/index.test.tsx
- src/pagination/__test__/utils.test.ts
- src/pagination/pagination.tsx
- autocomplete: добавлено переключение состояния при клике на поле
- pagination: добавлены unit-тесты
> Шаг 2 #314 Написать больше e2e-тестов

- .storybook/assets/styles/source-sans-pro.css
- .storybook/preview-head.html
- попытка восстановить шрифты в Storybook на GitHub
> Шаг 8 #314 Написать больше e2e-тестов

- src/chip/__stories__/index.stories.tsx
- src/chip/chip-util.scss
- src/chip/chip.module.scss
- src/chip/chip.tsx
- src/chip/index.ts
- src/chip/types.ts
- src/expandable/__stories__/index.stories.tsx
- src/group-overflow/__stories__/index.stories.tsx
- chip: добавлен компонент Chip по исправленным дизайн-гайдам
> Шаг 1 #345 Chips: обновить с соотвествии с испраленными дизайн-гайдами

- src/chip/__stories__/01-index.stories.tsx
- src/chip/__stories__/10-different-states.stories.tsx
- src/chip/__test__/index.test.tsx
- src/chip/chip.module.scss
- src/chip/chip.tsx
- src/chip/index.ts
- src/chip/types.ts
- src/chip/utils.tsx
- chip: добавлены стили для `:focus-visible`
- chip: добавлена утилита `getDeletableChipProps`
- chip: добавлены unit-тесты
> Шаг 3 #345 Chips: обновить с соотвествии с испраленными дизайн-гайдами

- src/carousel/__stories__/index.stories.tsx
- src/carousel/__test__/draggable.test.tsx
- src/carousel/draggable.tsx
- src/stroked-svg/index.tsx
- carousel: попытка исправить предотвращение blur на активном поле при клике на карусель
- stroked-svg: мелкие правки типов
> #352 Carousel: предотвращается blur у полей ввода при клике на карусель

- src/input/__stories__/index.stories.tsx
- src/pagination/__test__/index.test.tsx
- src/pagination/pagination.tsx
- pagination: правки обработки пропа getItems (patch)
- input: в сторибук добавлен пример без label и placeholder
> Шаг 3 #358 Отключить injectGlobals в Jest #358 

- src/top-bar/__stories__/index.stories.tsx
- src/top-bar/top-bar.module.scss
- src/top-bar/top-bar.tsx
- src/top-bar/types.ts
- top-bar: добавлена возможность задавать text-align и стили (minor)
>  Шаг 1 #355 Dropdown: доработать в соответствии с новыми дизайн-гайдами

- src/_internal/custom-scrollbar/custom-scrollbar.tsx
- src/_internal/custom-scrollbar/types.ts
- src/autocomplete/__stories__/index.stories.tsx
- src/autocomplete/autocomplete.tsx
- src/autocomplete/types.ts
- src/dropdown/dropdown.tsx
- src/dropdown/types.ts
- src/phone-input/__stories__/index.stories.tsx
- src/phone-input/phone-input.tsx
- src/phone-input/types.ts
- src/select/__stories__/index.stories.tsx
- src/select/parts/menu.tsx
- src/select/select.tsx
- src/select/types.ts
- internal/custom-scrollbar: добавлена возможность прокинуть viewportProps
- dropdown: добавлена возможность прокинуть viewportProps
- autocomplete: добавлена возможность прокинуть dropdownProps
- select: добавлена возможность прокинуть dropdownProps
- phone-input: добавлена возможность прокинуть dropdownProps
Closes #368
> Шаг 1 #368 Добавить возможность получать доступ к выпадающим спискам в полях 

- src/_internal/lifecycle/index.tsx
- src/autocomplete/__test__/index.test.tsx
- src/autocomplete/autocomplete.tsx
- src/autocomplete/types.ts
- src/phone-input/__test__/index.test.tsx
- src/phone-input/phone-input.tsx
- src/phone-input/types.ts
- src/select/__test__/index.test.tsx
- src/select/select.tsx
- src/select/types.ts
- autocomplete: добавлены пропсы onMenuOpen, onMenuClose
- select: добавлены пропсы onMenuOpen, onMenuClose
- phone-input: добавлены пропсы onMenuOpen, onMenuClose
> Шаг 2 #368 Добавить возможность получать доступ к выпадающим спискам в полях 

- src/autocomplete/__stories__/index.stories.tsx
- src/hooks/styles.ts
- src/modal-overlay/index.tsx
- src/modal/__stories__/13-full-scroll-handle.stories.tsx
- src/phone-input/__stories__/index.stories.tsx
- src/select/__stories__/index.stories.tsx
- правки stories для Autocomplete, PhoneInput, Select
- в stories для Modal добавлен пример с бесконечной прокруткой
>  Шаг 3 #353 BottomBar: добавить подписи под кнопками

- src/group-overflow/group-overflow.tsx
- src/group-overflow/index.ts
- src/group-overflow/types.ts
- src/info-text/index.ts
- src/info-text/info-text.tsx
- src/info-text/types.ts
- src/input/index.ts
- src/input/input.tsx
- src/input/types.ts
- src/layout/layout.tsx
- src/layout/legacy.tsx
- src/layout/types.ts
- src/link/index.ts
- src/link/link.tsx
- src/link/types.ts
- src/modal-overlay/index.ts
- src/modal-overlay/modal-overlay.tsx
- src/modal-overlay/types.ts
- `group-overflow`: добавлена точка входа `index.ts` (patch)
- `info-text`: добавлена точка входа `index.ts` (patch)
- `input`: добавлена точка входа `index.ts` (patch)
- `layout`: мелкие правки типов (patch)
- `link`: добавлена точка входа `index.ts` (patch)
- `modal-overlay`: добавлена точка входа `index.ts` (patch)
>  Шаг 2 Добавлены точки входа компонентам

- src/radio-button/index.ts
- src/radio-button/radio-button.tsx
- src/radio-button/types.ts
- src/range/index.ts
- src/range/range.tsx
- src/range/types.ts
- src/rating/index.ts
- src/rating/rating.tsx
- src/rating/types.ts
- src/side-page/index.ts
- src/side-page/side-page.tsx
- src/side-page/types.ts
- src/spinner/__test__/index.test.tsx
- src/spinner/index.ts
- src/spinner/spinner.tsx
- src/spinner/types.ts
- `radio-button`: добавлена точка входа `index.ts` (patch)
- `range`: добавлена точка входа `index.ts` (patch)
- `rating`: добавлена точка входа `index.ts` (patch)
- `side-page`: добавлена точка входа `index.ts` (patch)
- `spinner`: добавлена точка входа `index.ts` (patch)
- `spinner`: константа `DIAMETERS` переименована в `SPINNER_DIAMETER` (major)
>  Шаг 4 Добавлены точки входа компонентам #379 #380 

- jest.config.ts
- src/carousel/carousel.tsx
- src/carousel/index.ts
- src/carousel/types.ts
- src/text-button/index.ts
- src/text-button/text-button.tsx
- src/text-button/types.ts
- src/textarea/index.ts
- src/textarea/textarea.tsx
- src/textarea/types.ts
- src/timer/index.ts
- src/timer/timer.tsx
- src/timer/types.ts
- src/timer/utils.ts
- src/toggle/index.ts
- src/toggle/toggle.tsx
- src/toggle/types.ts
- src/unknown-content/index.ts
- src/unknown-content/types.ts
- src/unknown-content/unknown-content.tsx
- `carousel`: добавлена точка входа `index.ts` (patch)
- `text-button`: добавлена точка входа `index.ts` (patch)
- `textarea`: добавлена точка входа `index.ts` (patch)
- `timer`: добавлена точка входа `index.ts` (patch)
- `timer`: интерфейс  `Distance` переименован в `TimeDistance` (major)
- `toggle`: добавлена точка входа `index.ts` (patch)
- `unknown-content`: добавлена точка входа `index.ts` (patch)
>  Шаг 6 Добавлены точки входа компонентам

- src/arrow-button/types.ts
- src/base-input/types.ts
- src/bottom-bar/types.ts
- src/button/types.ts
- src/checkbox-field/index.tsx
- src/chips/chips.tsx
- src/dropdown-item/types.ts
- src/field-block/types.ts
- src/link/types.ts
- src/plate/types.ts
- src/price/types.ts
- src/rating/types.ts
- src/screen/index.tsx
- src/stepper/types.ts
- src/text-button/types.ts
- src/text-field/index.tsx
- src/top-bar/types.ts
- src/upload-area/types.ts
- повсеместно задействован WithTestId
> Шаг 2 #362 Сократить использование lodash

- src/context/index.ts
- src/dropdown/__test__/dropdown.test.tsx
- src/dropdown/__test__/utils.test.tsx
- src/dropdown/index.ts
- src/dropdown/utils.ts
- src/hooks/use-breakpoint/index.tsx
- src/hooks/use-breakpoint/utils.ts
- src/hooks/use-intersection/index.ts
- src/hooks/use-media/index.ts
- `dropdown`: доработки утилиты `useDropdownFloatingStyle`
- `context`: добавлены контексты для упрощения unit-тестирования браузерных API
- задействованы контексты в хуках
Closes #391
> #391 Select: при изменении ширины страницы меню не успевает синхронизировать ширину с открывающим элементом

- babel.config.js
- src/helpers/index.ts
- src/styling/index.ts
- добавлены точки входа для helpers и styling
>  Шаг 5 #401 Прибраться перед очередным релизом

- .storybook/main.js
- package-lock.json
- package.json
- src/helpers/__test__/format-date.test.ts
- src/helpers/format-date.ts
- src/helpers/get-date-interval-data.ts
- src/timer/__test__/utils.test.ts
- src/timer/utils.ts
- обновлен пакет date-fns (patch)
- отключена телеметрия storybook (patch)
Closes #418
> #418 Обновить date-fns 

- package-lock.json
- package.json
- src/arrow-button/__test__/__snapshots__/index.test.tsx.snap
- src/autocomplete/autocomplete.tsx
- src/button/__test__/index.test.tsx
- src/input/__stories__/index.stories.tsx
- src/input/input.tsx
- src/pagination/pagination.tsx
- src/panel/__test__/__snapshots__/index.test.tsx.snap
- src/phone-input/phone-input.tsx
- src/select/parts/block.tsx
- src/select/parts/button.tsx
- src/stroked-svg/__stories__/index.stories.tsx
- обновлен пакет иконок (major)
- обновлены импорты иконок (patch)
Closes #436
> #436 Обновлен пакет иконок

- src/expandable/__test__/utils.test.tsx
- src/expandable/utils.ts
- expandable: добавлена проверка отключенности наблюдения (patch)
Closes #444
> #444 Expandable: не вызывать callback если механизм выключен 

- src/autocomplete/autocomplete.tsx
- src/autocomplete/menu.tsx
- src/dropdown/__test__/utils.test.tsx
- src/dropdown/index.ts
- src/dropdown/types.ts
- src/dropdown/utils.ts
- src/hint/hint.tsx
- src/popup/popup.tsx
- src/select/parts/menu.tsx
- src/select/select.tsx
- src/select/types.ts
- hint: портал выводится только если хинт показан (patch)
- popup: портал выводится только если попап показан (patch)
- autocomplete: портал выводится только если меню показано (patch)
- select: портал выводится только если меню показано (patch)
- dropdown: добавлен хук useDismissByWheel (minor)
Closes #447
> #447 Не выводить порталы если выпадающий элемент не показан 

- package-lock.json
- package.json
- src/_internal/custom-scrollbar/__test__/index.test.tsx
- src/_internal/custom-scrollbar/custom-scrollbar.tsx
- обновлены пакеты overlayscrollbars и overlayscrollbars-react (major)
- _internal: добавлен костыль для работы с overlayscrollbars в CustomScrollbar
Closes #449
> #449 Обновить overlayscrollbars

- .jest/setup.js
- src/context/index.ts
- src/masked-input/masked-input.tsx
- src/stroked-svg/stroked-svg.tsx
- stroked-svg: если обводка 0 то копия не выводится (нужно чтобы выключать обводку без необходимости выводить svg вместо StrokedSVG)
- context: мелкие todo
- masked-input: мелкие todo
- фикс конфига jest
> Мелкие патчи и todo

- docs/package-lock.json
- docs/package.json
- docs/rspack.config.ts
- package-lock.json
- выполнен npm audit fix в корне и в docs
- docs: обновлен rspack для решения проблемы с незавершающимся процессом сборки
> Выполнен npm audit fix

- src/dropdown-item/utils.ts
- src/masked-input/masked-input.tsx
- src/masked-input/use-input-mask.ts
- src/masked-input/utils.ts
- src/phone-input/__test__/preset.test.ts
- src/phone-input/__test__/utils.test.ts
- src/phone-input/utils.ts
- masked-input: стилистические правки (patch)
- phone-input: правки работы функции определения маски и тесты (patch)
- phone-input: добавлены тесты для фиксации идентичности пресетов масок (patch)
Closes #271
> Шаг 2 #271 phone-input: Добавить возможность задавать варианты масок и вынести картинки в отдельный модуль

- docs/stories/components/skeleton/01-primary.story.tsx
- docs/stories/components/skeleton/02-complex.story.tsx
- docs/stories/components/skeleton/03-complex-dark.story.tsx
- docs/stories/components/skeleton/test-ratio.story.tsx
- src/skeleton/index.ts
- src/skeleton/skeleton.m.scss
- src/skeleton/skeleton.tsx
- src/skeleton/types.ts
- добавлен компонент Skeleton (черновик) (minor)
> Шаг 1 #453  Добавить компонент Skeleton 

- .github/workflows/gh-pages.yml
- ci: обновлен action JamesIves/github-pages-deploy-action (patch)
> Шаг 2 #453 Добавить компонент Skeleton

- docs/stories/components/skeleton/04-multiple-skeletons.story.tsx
- docs: для Skeleton добавлен пример композиции (patch)
> Шаг 3 #453 Добавить компонент Skeleton

- package-lock.json
- package.json
- src/masked-input/masked-input.tsx
- src/masked-input/types.ts
- src/masked-input/use-input-mask.ts
- src/masked-input/utils.ts
- tsconfig.base.json
- обновлен пакет @krutoo/input-mask (patch)
- обновлен ts
- правки конфига ts
> Обновлен пакет @krutoo/input-mask

- docs/package-lock.json
- docs/package.json
- package-lock.json
- package.json
- src/arrow-button/arrow-button.m.scss
- src/chip/chip.m.scss
- src/info-text/info-text.m.scss
- src/popup/popup-view.m.scss
- src/text-button/text-button.m.scss
- обновлены пакеты sass (patch)
- обновлены стили для устранения варингов sass (patch)
- deps: обновлены пакеты sass (patch)
Closes #467
> #467 Обновить стили для удаления варнингов Sass

- docs/package-lock.json
- docs/package.json
- docs: обновлены зависимости для npm audit
> Шаг 2 #469

- .template/data.mjs
- src/colors.scss
- src/colors/index.ts
- src/gradients.scss
- src/gradients/index.ts
- gradients: добавлен новый градиент blueberry (minor)
> #480 Tokens: добавить новый градиент

- src/chip/chip.m.scss
- chip: добавлена плавность изменения цвета и фона (minor)
Closes #482
> #482 Chip: доработать анимацию 

- src/select/parts/menu.tsx
- src/select/select.tsx
- select: исправлены скачки в хроме при открытии меню
> #487 Select: исправить скачки страницы наверх при открытии меню в Chrome 

- src/hint/utils.ts
переданы аргументы в функцию autoUpdate для корректного перерасчета позиции с заданным placement
> #11682 Hint с позиционированием, некорректный расчет позиции

- docs/package-lock.json
- docs/stories/components/carousel/03-vertical.story.tsx
- docs/stories/components/carousel/stories.m.scss
- package-lock.json
- src/carousel/carousel.tsx
- поправлена логика расчета отображения кнопки 
- прогнан `npm audit fix`
- добавлен `story book` кейс без кнопок и поправлена высота (с учетом отступа)
> #11791 Некорректно смещается карусель при прокручивании к последнему элементу

- docs/package-lock.json
- docs/package.json
- package-lock.json
- package.json
- src/autocomplete/index.ts
- src/autocomplete/index.tsx
- src/bottom-bar/bottom-bar.m.scss
- src/phone-input/index.ts
- src/styling/colors.m.scss
- добавлены эскпорты
- обновлен `sass` и поправлены ворнинги
> #11876 ui-nucleons: добавить отсутствующие экспорты

- src/_internal/page-scroll-lock/adapters/__test__/ui-nucleons.test.ts
- src/carousel/__test__/index.test.tsx
- src/dropdown-item/__test__/index.test.tsx
- src/dropdown/__test__/utils.test.tsx
- src/hooks/use-breakpoint/__test__/index.test.tsx
- src/hooks/use-intersection/__test__/test-utils.test.ts
Исправлены ошибки и варнинги в тестах
https://github.com/user-attachments/assets/c781c5d9-9bbe-4e90-9b33-9fee098acbca
> Исправление ошибок и предупреждений в тестах  #12526

- src/hooks/use-intersection/test-utils.ts
- поправлен импорт act в intersectionMock для исправления варнингов в молекулах
> Для исправления предупреждений в moleculas
